import { BranchStats, FIXED_BRANCHES } from "./types";

export const SAMPLE_BRANCHESTATS: BranchStats[] = [
  // 서울 권역
  {
    id: "br_1",
    name: "서울강남",
    region: "서울",
    terminations: 260,
    employedRaw: 216,
    employedSpecial: 0,
    employedExcluded: 66,
    jobPlacementRaw: 27,
    jobPlacementNew: 0,
    earlyEmployedRaw: 12,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 54,
    wageTotal2025: 0,
    wageTotal2026: 260,
    retention6Months: 21,
    satisfactionScore: 9.4,
    iapEstablished: 118,
    dropoutCount: 5,
    bestPracticeCount: 1,
    bestPracticeAward: "best", // 최우수 (1점)
    otherProjectLinkedCount: 3
  },
  {
    id: "br_2",
    name: "서울관악",
    region: "서울",
    terminations: 443,
    employedRaw: 291,
    employedSpecial: 1,
    employedExcluded: 16,
    jobPlacementRaw: 44,
    jobPlacementNew: 0,
    earlyEmployedRaw: 76,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 109,
    wageTotal2025: 0,
    wageTotal2026: 443,
    retention6Months: 46,
    satisfactionScore: 9.1,
    iapEstablished: 140,
    dropoutCount: 8,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 2
  },
  {
    id: "br_3",
    name: "서울남부",
    region: "서울",
    terminations: 380,
    employedRaw: 241,
    employedSpecial: 1,
    employedExcluded: 33,
    jobPlacementRaw: 23,
    jobPlacementNew: 0,
    earlyEmployedRaw: 37,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 73,
    wageTotal2025: 0,
    wageTotal2026: 380,
    retention6Months: 33,
    satisfactionScore: 8.9,
    iapEstablished: 108,
    dropoutCount: 4,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 1
  },
  {
    id: "br_4",
    name: "서울동부",
    region: "서울",
    terminations: 318,
    employedRaw: 212,
    employedSpecial: 0,
    employedExcluded: 27,
    jobPlacementRaw: 15,
    jobPlacementNew: 0,
    earlyEmployedRaw: 45,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 77,
    wageTotal2025: 0,
    wageTotal2026: 318,
    retention6Months: 27,
    satisfactionScore: 8.8,
    iapEstablished: 92,
    dropoutCount: 6,
    bestPracticeCount: 1,
    bestPracticeAward: "normal", // 장려 (0.5점)
    otherProjectLinkedCount: 1
  },
  {
    id: "br_5",
    name: "서울북부",
    region: "서울",
    terminations: 405,
    employedRaw: 250,
    employedSpecial: 0,
    employedExcluded: 14,
    jobPlacementRaw: 39,
    jobPlacementNew: 0,
    earlyEmployedRaw: 54,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 72,
    wageTotal2025: 0,
    wageTotal2026: 405,
    retention6Months: 36,
    satisfactionScore: 9.2,
    iapEstablished: 128,
    dropoutCount: 9,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 2
  },
  {
    id: "br_6",
    name: "서울서부",
    region: "서울",
    terminations: 416,
    employedRaw: 306,
    employedSpecial: 1,
    employedExcluded: 35,
    jobPlacementRaw: 41,
    jobPlacementNew: 0,
    earlyEmployedRaw: 54,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 70,
    wageTotal2025: 0,
    wageTotal2026: 416,
    retention6Months: 54,
    satisfactionScore: 9.0,
    iapEstablished: 102,
    dropoutCount: 4,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 1
  },

  // 경기 권역
  {
    id: "br_7",
    name: "경기고양",
    region: "경기",
    terminations: 302,
    employedRaw: 245,
    employedSpecial: 1,
    employedExcluded: 69,
    jobPlacementRaw: 45,
    jobPlacementNew: 0,
    earlyEmployedRaw: 41,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 62,
    wageTotal2025: 0,
    wageTotal2026: 302,
    retention6Months: 19,
    satisfactionScore: 9.3,
    iapEstablished: 114,
    dropoutCount: 6,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 3
  },
  {
    id: "br_8",
    name: "경기남양주",
    region: "경기",
    terminations: 286,
    employedRaw: 205,
    employedSpecial: 0,
    employedExcluded: 9,
    jobPlacementRaw: 45,
    jobPlacementNew: 0,
    earlyEmployedRaw: 59,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 52,
    wageTotal2025: 0,
    wageTotal2026: 286,
    retention6Months: 33,
    satisfactionScore: 8.6,
    iapEstablished: 98,
    dropoutCount: 5,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 1
  },
  {
    id: "br_9",
    name: "경기성남",
    region: "경기",
    terminations: 467,
    employedRaw: 378,
    employedSpecial: 0,
    employedExcluded: 99,
    jobPlacementRaw: 39,
    jobPlacementNew: 0,
    earlyEmployedRaw: 52,
    earlyEmployedSpecial: 1,
    wageQualified2025: 0,
    wageQualified2026: 103,
    wageTotal2025: 0,
    wageTotal2026: 467,
    retention6Months: 52,
    satisfactionScore: 9.5,
    iapEstablished: 134,
    dropoutCount: 5,
    bestPracticeCount: 1,
    bestPracticeAward: "excellent", // 우수 (0.7점)
    otherProjectLinkedCount: 4
  },
  {
    id: "br_10",
    name: "경기안산",
    region: "경기",
    terminations: 363,
    employedRaw: 279,
    employedSpecial: 1,
    employedExcluded: 65,
    jobPlacementRaw: 43,
    jobPlacementNew: 0,
    earlyEmployedRaw: 67,
    earlyEmployedSpecial: 1,
    wageQualified2025: 0,
    wageQualified2026: 84,
    wageTotal2025: 0,
    wageTotal2026: 363,
    retention6Months: 34,
    satisfactionScore: 9.0,
    iapEstablished: 122,
    dropoutCount: 7,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 2
  },
  {
    id: "br_11",
    name: "경기안양",
    region: "경기",
    terminations: 303,
    employedRaw: 228,
    employedSpecial: 1,
    employedExcluded: 24,
    jobPlacementRaw: 41,
    jobPlacementNew: 0,
    earlyEmployedRaw: 56,
    earlyEmployedSpecial: 1,
    wageQualified2025: 0,
    wageQualified2026: 73,
    wageTotal2025: 0,
    wageTotal2026: 303,
    retention6Months: 27,
    satisfactionScore: 8.7,
    iapEstablished: 88,
    dropoutCount: 3,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 1
  },
  {
    id: "br_12",
    name: "경기의정부",
    region: "경기",
    terminations: 359,
    employedRaw: 282,
    employedSpecial: 0,
    employedExcluded: 35,
    jobPlacementRaw: 54,
    jobPlacementNew: 0,
    earlyEmployedRaw: 84,
    earlyEmployedSpecial: 1,
    wageQualified2025: 0,
    wageQualified2026: 71,
    wageTotal2025: 0,
    wageTotal2026: 359,
    retention6Months: 30,
    satisfactionScore: 8.9,
    iapEstablished: 108,
    dropoutCount: 8,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 2
  },
  {
    id: "br_13",
    name: "경기화성",
    region: "경기",
    terminations: 357,
    employedRaw: 325,
    employedSpecial: 1,
    employedExcluded: 66,
    jobPlacementRaw: 48,
    jobPlacementNew: 0,
    earlyEmployedRaw: 63,
    earlyEmployedSpecial: 1,
    wageQualified2025: 0,
    wageQualified2026: 93,
    wageTotal2025: 0,
    wageTotal2026: 357,
    retention6Months: 38,
    satisfactionScore: 9.1,
    iapEstablished: 125,
    dropoutCount: 6,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 3
  },
  {
    id: "br_14",
    name: "경기수원",
    region: "경기",
    terminations: 19,
    employedRaw: 95,
    employedSpecial: 1,
    employedExcluded: 79,
    jobPlacementRaw: 4,
    jobPlacementNew: 0,
    earlyEmployedRaw: 16,
    earlyEmployedSpecial: 1,
    wageQualified2025: 0,
    wageQualified2026: 5,
    wageTotal2025: 0,
    wageTotal2026: 19,
    retention6Months: 0,
    satisfactionScore: 9.2,
    iapEstablished: 136,
    dropoutCount: 10,
    bestPracticeCount: 1,
    bestPracticeAward: "target", // 대상 (2점)
    otherProjectLinkedCount: 3
  },
  {
    id: "br_15",
    name: "경기평택",
    region: "경기",
    terminations: 14,
    employedRaw: 39,
    employedSpecial: 0,
    employedExcluded: 24,
    jobPlacementRaw: 5,
    jobPlacementNew: 0,
    earlyEmployedRaw: 15,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 4,
    wageTotal2025: 0,
    wageTotal2026: 14,
    retention6Months: 0,
    satisfactionScore: 8.8,
    iapEstablished: 101,
    dropoutCount: 5,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 2
  },

  // 중부(인천) 권역
  {
    id: "br_16",
    name: "인천부평",
    region: "중부(인천)",
    terminations: 554,
    employedRaw: 493,
    employedSpecial: 1,
    employedExcluded: 158,
    jobPlacementRaw: 54,
    jobPlacementNew: 0,
    earlyEmployedRaw: 59,
    earlyEmployedSpecial: 1,
    wageQualified2025: 0,
    wageQualified2026: 101,
    wageTotal2025: 0,
    wageTotal2026: 554,
    retention6Months: 38,
    satisfactionScore: 9.0,
    iapEstablished: 118,
    dropoutCount: 6,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 3
  },
  {
    id: "br_17",
    name: "인천지점",
    region: "중부(인천)",
    terminations: 14,
    employedRaw: 33,
    employedSpecial: 0,
    employedExcluded: 20,
    jobPlacementRaw: 3,
    jobPlacementNew: 0,
    earlyEmployedRaw: 13,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 8,
    wageTotal2025: 0,
    wageTotal2026: 14,
    retention6Months: 0,
    satisfactionScore: 8.7,
    iapEstablished: 92,
    dropoutCount: 4,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 1
  },

  // 대구(경북) 권역
  {
    id: "br_18",
    name: "대구동부",
    region: "대구(경북)",
    terminations: 336,
    employedRaw: 216,
    employedSpecial: 1,
    employedExcluded: 40,
    jobPlacementRaw: 33,
    jobPlacementNew: 0,
    earlyEmployedRaw: 35,
    earlyEmployedSpecial: 1,
    wageQualified2025: 0,
    wageQualified2026: 50,
    wageTotal2025: 0,
    wageTotal2026: 336,
    retention6Months: 27,
    satisfactionScore: 8.5,
    iapEstablished: 106,
    dropoutCount: 9,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 1
  },
  {
    id: "br_19",
    name: "포항지점",
    region: "대구(경북)",
    terminations: 12,
    employedRaw: 19,
    employedSpecial: 0,
    employedExcluded: 10,
    jobPlacementRaw: 2,
    jobPlacementNew: 0,
    earlyEmployedRaw: 9,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 3,
    wageTotal2025: 0,
    wageTotal2026: 12,
    retention6Months: 0,
    satisfactionScore: 8.4,
    iapEstablished: 80,
    dropoutCount: 7,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 1
  },

  // 대전(충청·세종) 권역
  {
    id: "br_20",
    name: "대전지점",
    region: "대전(충청·세종)",
    terminations: 229,
    employedRaw: 178,
    employedSpecial: 0,
    employedExcluded: 38,
    jobPlacementRaw: 17,
    jobPlacementNew: 0,
    earlyEmployedRaw: 35,
    earlyEmployedSpecial: 1,
    wageQualified2025: 0,
    wageQualified2026: 39,
    wageTotal2025: 0,
    wageTotal2026: 229,
    retention6Months: 11,
    satisfactionScore: 9.1,
    iapEstablished: 126,
    dropoutCount: 8,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 3
  },

  // 부산(경남·울산) 권역
  {
    id: "br_21",
    name: "부산남구",
    region: "부산(경남·울산)",
    terminations: 137,
    employedRaw: 136,
    employedSpecial: 0,
    employedExcluded: 57,
    jobPlacementRaw: 10,
    jobPlacementNew: 0,
    earlyEmployedRaw: 20,
    earlyEmployedSpecial: 1,
    wageQualified2025: 0,
    wageQualified2026: 25,
    wageTotal2025: 0,
    wageTotal2026: 137,
    retention6Months: 13,
    satisfactionScore: 8.3,
    iapEstablished: 101,
    dropoutCount: 8,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 1
  },
  {
    id: "br_22",
    name: "부산북부",
    region: "부산(경남·울산)",
    terminations: 97,
    employedRaw: 85,
    employedSpecial: 1,
    employedExcluded: 26,
    jobPlacementRaw: 8,
    jobPlacementNew: 0,
    earlyEmployedRaw: 22,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 18,
    wageTotal2025: 0,
    wageTotal2026: 97,
    retention6Months: 10,
    satisfactionScore: 8.5,
    iapEstablished: 87,
    dropoutCount: 6,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 1
  },
  {
    id: "br_23",
    name: "부산동부",
    region: "부산(경남·울산)",
    terminations: 5,
    employedRaw: 52,
    employedSpecial: 0,
    employedExcluded: 51,
    jobPlacementRaw: 0,
    jobPlacementNew: 0,
    earlyEmployedRaw: 1,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 1,
    wageTotal2025: 0,
    wageTotal2026: 5,
    retention6Months: 0,
    satisfactionScore: 8.6,
    iapEstablished: 112,
    dropoutCount: 9,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 2
  },
  {
    id: "br_24",
    name: "울산지점",
    region: "부산(경남·울산)",
    terminations: 6,
    employedRaw: 11,
    employedSpecial: 0,
    employedExcluded: 7,
    jobPlacementRaw: 0,
    jobPlacementNew: 0,
    earlyEmployedRaw: 3,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 4,
    wageTotal2025: 0,
    wageTotal2026: 6,
    retention6Months: 0,
    satisfactionScore: 8.2,
    iapEstablished: 97,
    dropoutCount: 12,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 1
  }
];

export function getEmptyBranchStats(): BranchStats[] {
  return FIXED_BRANCHES.map((b, idx) => ({
    id: `br_empty_${idx + 1}`,
    name: b.name,
    region: b.region,
    terminations: 0,
    employedRaw: 0,
    employedSpecial: 0,
    employedExcluded: 0,
    jobPlacementRaw: 0,
    jobPlacementNew: 0,
    earlyEmployedRaw: 0,
    earlyEmployedSpecial: 0,
    wageQualified2025: 0,
    wageQualified2026: 0,
    wageTotal2025: 0,
    wageTotal2026: 0,
    retention6Months: 0,
    satisfactionScore: 0,
    iapEstablished: 0,
    dropoutCount: 0,
    bestPracticeCount: 0,
    bestPracticeAward: "none",
    otherProjectLinkedCount: 0
  }));
}
